### PR TITLE
Fixed : "To merge the changes ( - Until September 30)."  #185 

### LINKED ISSUE #185: To merge the changes ( - Until September 30)
# Requirement
Like this : https://github.com/OpenTouryoProject/OpenTouryo/issues/131

### PR DESCRIPTION
**Pull request by daisukenishino**
# Fixes
Fixed #185

# pull-requests
- [Merged Cross-browser-compatible correspondence function changes to root by comparing with C# version. #145](https://github.com/SymphonyTeleca/OpenTouryo/pull/145)
- [Removed unwanted code(ByVal changes) from ProjectX_sample to maintain consistency.
#146](https://github.com/SymphonyTeleca/OpenTouryo/pull/146)
- [Modified Implemented string to implemented in PublicExceptionMessageResource file
#147](https://github.com/SymphonyTeleca/OpenTouryo/pull/147)
- [Corrected comment header in C# and added comment header in VB #148](https://github.com/SymphonyTeleca/OpenTouryo/pull/148)
- [Modified Comment history in root for C# and VB version as per review comment. #151](https://github.com/SymphonyTeleca/OpenTouryo/pull/151)

### Fixes of found problems 
- [Fixed the issue identified in Global.asax and App_Code in root C# #149](https://github.com/SymphonyTeleca/OpenTouryo/pull/149)
- [Fixed the issue identified in Global.asax and App_Code in root for VB #150](https://github.com/SymphonyTeleca/OpenTouryo/pull/150)

### Supplementary explanation of [#145](https://github.com/SymphonyTeleca/OpenTouryo/pull/145)
The additional following fixes have been performed in this.
- Global.asax.cs(vb) was separated as the code-behind.
- AssemblyInfo.vb has been added to the ProjectX_sample of the VB.

### CODE REVIEW

File: root/programs/VB/Samples/WebApp_sample/ProjectX_sample/App_Code/sample/Dao/LayerD.vb [hunk 1]
```diff
@@ -118,15 +118,15 @@ Public Class LayerD
...
     ''' <param name="testParameter">引数クラス</param>
     ''' <param name="testReturn">戻り値クラス</param>
-    Public Sub SelectCount(ByVal testParameter As TestParameterValue, ByVal testReturn As TestReturnValue)
+    Public Sub SelectCount(testParameter As TestParameterValue, testReturn As TestReturnValue)
         ' ↓DBアクセス-----------------------------------------------------
 
         Dim filename As String = ""
 
-        If (testParameter.ActionType.Split("%"c))(2) = "static" Then
+        If (testParameter.ActionType.Split("%"C))(2) = "static" Then
```
Comment (yusukemaegawa) [inline root/programs/VB/Samples/WebApp_sample/ProjectX_sample/App_Code/sample/Dao/LayerD.vb]: @daisukenishino 

When implementing in this way, Visual Studio converts the program as follows forcibly.
```vb
If (testParameter.ActionType.Split("%"c))(2) = "static" Then
```

Therefore, I think that this revision is unnecessary.

Comment (daisukenishino) [inline root/programs/VB/Samples/WebApp_sample/ProjectX_sample/App_Code/sample/Dao/LayerD.vb]: @yusukemaegawa 

This purpose was to eliminate the difference.
But, this did not be adjusted to "default side".

But, this changes passed the build process.
And, there is no problem on behavior.

Therefore, this time, I request you to merge this pullrequest in this state.

File: root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/sample/3Tier/ProductsConditionalSearch.aspx.vb [hunk 2]
```diff
@@ -161,7 +161,7 @@ Partial Public Class ProductsConditionalSearch
             Return DirectCast(Session("ddldsdt_SupplierID"), DataTable)
         End Get
         Set(value As DataTable)
-            Session("ddldsdt_SupplierID") = value
+            Session("ddldsdt_SupplierID") = Value
```
Comment (daisukenishino) [inline root/programs/VB/Samples/WebApp_sample/ProjectX_sample/Aspx/sample/3Tier/ProductsConditionalSearch.aspx.vb]: same as above.
