### PR TITLE
Fixed : "Replace window.showModalDialog that is used from dialog display functions." #236

### LINKED ISSUE #236: Replace window.showModalDialog that is used from dialog display functions.
# Requirement
- It seems there are needs,  
so I will enhance dialog display functions by replace window.showModalDialog.
- Since this cannot call synchronously like showModalDialog,  
set up a callback and, run it as the post-processing.

### OK and YES/NO Message dialog
Change it to the pseudo dialog by using the floating div.

### Business modal dialog
- Change it to the pseudo dialog by using the window.open.
- When replacing window.open, set a callback in the onUnload event.  
See : サブウィンドウが閉じた時に親ウィンドウでイベントを発火する - Qiita  
http://qiita.com/bgn_nakazato/items/0b0c1b8a23dcaa7959df

### PR DESCRIPTION
**Pull request by daisukenishino**
fixed #236

Do not merge this pull request yet.

- Corresponded to OK and YES / NO pseudo dialogs.
- Tomorrow, I will corresponded to Business pseudo dialogs by window.open.

### CODE REVIEW

**Comment by yusukemaegawa** [comment]
@daisukenishino 

Why don't you use [Modals](http://getbootstrap.com/javascript/#modals) of Bootstrap?

**Comment by daisukenishino** [comment]
@yusukemaegawa 

Because I thought that my simple implementation was safer for future maintenance.
If you think it should be do, please explain the proposal of bootstrap is more appropriate.

**Comment by yusukemaegawa** [comment]
@daisukenishino 

Open Touryo 2.0 has supported Bootstrap thoroughly.
So, using the Modal of Bootstrap, I think the development style and the design can be unified.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

Can Bootstrap's Dialog be equipped with IFRAME?
In this time, IFRAME is put on above of the pseudo dialog for use the existing * .aspx.

**Comment by yusukemaegawa** [comment]
@daisukenishino 

Will the following pages help you?

- [iFrame inside Bootstrap 3 modal - CodePen](https://codepen.io/filippoq/pen/QwogWz/)
- [Bootstrap iFrame inside modal snippet - yV6gTT5Faw - Bootply](http://www.bootply.com/61676)

You can find the various pages by searching with appropriate keywords, e.g. "bootstrap modal iframe".

**Comment by daisukenishino** [comment]
@yusukemaegawa 

I think the next two points are problems. Therefore, I will not use Bootstrap's modal.
- Investigation is necessary for fitting with this library.
- I do not want to use modules with a lot of dependency on the processing of the foundation.

The following restrictions are imposed on the "business modal dialog" function by the window.open method on the modern browsers.
- If the "business modal dialog" was closed with the [x] button, then the parent can not be operated. Therefore, in this case, it is necessary to solve this problem by reloading the parent screen or closing it with the [x] button.
- BaseController.CloseModalScreen_WithAllParent() method no longer supports to close "business modal dialogs".

File: root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Scripts/touryo/common.js [hunk 1]
```diff
@@ -433,50 +490,179 @@ function Fx_DisplayProgressDialog() {
...
+    // OK Pseudo Dialog ----------------------------------------------------
+     
+    _div = document.createElement("div");
+    _div.id = "AjaxOKPseudoDialog";
+
+    // 幅を指定
+    _div.style.width = AjaxOKPseudoDialog_Width + "px";
+    _div.style.height = AjaxOKPseudoDialog_Height + "px";
+
+    // スタイルを指定
```
Comment (yusukemaegawa) [inline root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Scripts/touryo/common.js]: @daisukenishino 

Most developers may think that the styles are defined in css file.
It might be a good idea to add class to `_div` and set style in css file (except *width* and *height*).

- JavaScript
```JavaScript
_div.className = "xxx";
```

- CSS
```css
.xxx {
  top: 0px;
  left: 0px;
  ...
}
```

**Comment by yusukemaegawa** [comment]
@daisukenishino 

I think that the following behaviors are not correct.
- Click *ImageButton* in *子画面表示*.
- Parent window is masked and launch *modeless* dialog.
- Close the modeless dialog.
- Parent window is *still* masked.

**Comment by yusukemaegawa** [comment]
@daisukenishino 

The following error occurs when clicking *ImageButton* in ファイルのダウンロード.

```txt
複数のコンテンツが ContentPlaceHolder_A に適用されています。
```

File: root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Scripts/touryo/common.js (hunk 1 above)
Comment (daisukenishino) [inline root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Scripts/touryo/common.js]: @yusukemaegawa 

I see, I add it below file.
- \root\programs\C#\Samples\WebApp_sample\ProjectX_sample\Content\touryo\Style.css"

**Comment by daisukenishino** [comment]
@yusukemaegawa 

- [comment1](#issuecomment-300375492)
[This is a limitation.](#issuecomment-297636800)
- [comment2](#issuecomment-300375720)
I found the following duplication at testDLScreen.aspx. I will fix these problems.
```
\root\programs\C#\Samples\WebApp_sample\ProjectX_sample\Aspx\testFxLayerP\testDLScreen.aspx(3,57)  [UTF-8]: <asp:Content ID="cphHeaderScripts" ContentPlaceHolderID="ContentPlaceHolder_A" Runat="Server">
\root\programs\C#\Samples\WebApp_sample\ProjectX_sample\Aspx\testFxLayerP\testDLScreen.aspx(7,17)  [UTF-8]: <asp:Content ID="ContentPlaceHolder_A" ContentPlaceHolderID="ContentPlaceHolder_A" Runat="Server">
```

**Comment by daisukenishino** [comment]
@yusukemaegawa 

Fixed. Please check and merge.

File: root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Scripts/touryo/common.js [hunk 2]
```diff
@@ -603,81 +684,206 @@ function Fx_ShowMessageDialog(url) {
     url = url + "&Time=" + year_now + month_now + date_now + day_now + hour_now + minute_now + second_now;
 
     // マスクする。
-    Fx_MaskOn();
+    Fx_DialogMaskOn();
```
Comment (yusukemaegawa) [inline root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Scripts/touryo/common.js]: @daisukenishino 

When users can scroll horizontally on parent screen, the width of mask is incorrect. So, user can operate the controls in the area that is not masked.

image

Comment (daisukenishino) [inline root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Scripts/touryo/common.js]: @yusukemaegawa 

We use the following method to determine the size.
- Fx_getContentsHeight()
- Fx_getBrowserWidth()

More appropriate implementation may be possible.

Comment (yusukemaegawa) [inline root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Scripts/touryo/common.js]: @daisukenishino 

It might be a good idea to use `scrollWidth` method instead of `window.innerWidth` or `clientWidth`.

See also: [javascript jQuery スクロールバーの幅を含むウィンドウサイズを取得したい。](http://chaika.hatenablog.com/entry/2015/02/12/054602)

**Comment by yusukemaegawa** [comment]
@daisukenishino 

I think that the pseudo dialog is not stylish.
It might be a good idea to modify as follows: 

- Overview
    - Add dialog title area
    - Fix the buttons on the bottom of dialog
    - Use *Bootstrap css* for the style of buttons
    - Use *border-radius* property and *box-shadow* property.
    - Change the background color of dialog from lightcyan to White

- myOKMessageDialog.aspx
```html
<div style="text-align:left; min-height: 90%; height: auto; margin: 0 auto -40px; padding: 0 0 40px;">
    <div style="font-size: large"><%= ConfigurationManager.AppSettings["BrowserTitle"] %></div>
    <hr />
    <table style="border-spacing:10px; border-collapse:collapse;" border="0">
        <tr>
            <td rowspan="2">
                <asp:Image ID="imgIcon" runat="server" />
            </td>
            <td>
                <cc1:WebCustomLabel ID="lblmessageID" runat="server" Text="Label"></cc1:WebCustomLabel>
            </td>
        </tr>
        <tr>
            <td>
                <cc1:WebCustomLabel ID="lblmessage" runat="server" Text="Label"></cc1:WebCustomLabel>
            </td>
        </tr>
    </table>
</div>
<br />
<div style="text-align:center; height: 40px;">
    <input type="button" class="btn btn-primary" id="Button1" name="btnOK" value="OK" onclick="onOK();" tabindex="1" style="width: 100px" />
</div>
```

- myYesNoMessageDialog.aspx
```html
<div style="text-align:left; min-height: 90%; height: auto; margin: 0 auto -40px; padding: 0 0 40px;">
    <div style="font-size: large"><%= ConfigurationManager.AppSettings["BrowserTitle"] %></div>
    <hr />
    <table style="border-spacing:10px; border-collapse:collapse;" border="0">
        <tr>
            <td rowspan="2">
                <asp:Image ID="imgIcon" runat="server" />
            </td>
            <td>
                <cc1:WebCustomLabel ID="lblmessageID" runat="server" Text="Label"></cc1:WebCustomLabel>
            </td>
        </tr>
        <tr>
            <td>
                <cc1:WebCustomLabel ID="lblmessage" runat="server" Text="Label"></cc1:WebCustomLabel>
            </td>
        </tr>
    </table>
</div>
<br />
<div style="text-align:center; height: 40px;">
    <input type="button" class="btn btn-primary" id="btnYes" name="btnYes" value="はい" onclick="onYes();" tabindex="1" style="width: 100px" />
    <input type="button" class="btn btn-primary" id="btnNo" name="btnNo" value="いいえ" onclick="onNo();" tabindex="2" style="width: 100px" />
</div>
```

- Style.css
```css
.ok-dialog
{
    position         : fixed;
    top              : 0;
    left             : 0;
    padding          : 10px 10px 0 10px;
    text-align       : center;
    overflow         : hidden;                 /* hiddenに変更*/
    /* background-color : lightcyan; */
    background-color : White;
    z-index          : 1001;                   /* dialog-maskより前面に出す。*/

    /* 角丸四角 */
    border-radius: 10px;
    -webkit-border-radius: 10px;
    -moz-border-radius: 10px;

    /* 影 */
    box-shadow: 10px 10px 10px rgba(0,0,0,0.6);
}

.ok-dialog iframe {
    border: none;
}

.yesno-dialog
{
    position         : fixed;
    top              : 0;
    left             : 0;
    padding          : 10px 10px 0 10px;
    text-align       : center;
    overflow         : hidden;                 /* hiddenに変更*/
    /* background-color : lightcyan; */
    background-color : White;
    z-index          : 1001;                   /* dialog-maskより前面に出す。*/

    /* 角丸四角 */
    border-radius: 10px;
    -webkit-border-radius: 10px;
    -moz-border-radius: 10px;

    /* 影 */
    box-shadow: 10px 10px 10px rgba(0,0,0,0.6);
}

.yesno-dialog iframe {
    border: none;
}
```

- Execution image
image  
  
  image

**Comment by daisukenishino** [comment]
@yusukemaegawa 

I agreed with the above, and I fixed the style of pseudo dialog.
In addition, the fix was not reflecting to the VB version.
I request you to merge after confirming the operation of VB  version and MVC.

File: root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Aspx/Framework/myOKMessageDialog.aspx [hunk 3]
```diff
@@ -5,28 +5,51 @@
...
+    </head>
         
-        //-->
-    </script>
-    <body>
-        <div style="text-align:left">
-            <table style="border-spacing:10px; border-collapse:collapse;" border="0">
+    <body onload="Document_OnLoad();">
+        <div style="text-align:left;">
+            <div id="PseudoDialogTitle"></div>
```
Comment (yusukemaegawa) [inline root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Aspx/Framework/myOKMessageDialog.aspx]: @daisukenishino 

The style of this `<div id="PseudoDialogTitle">` tag is different from the one of myYesNoMessageDialog.aspx. I think that these styles should be unified as the one of myYesNoMessageDialog.aspx, that is, add `style="font-size: large"`.

- myOKMessageDialog.aspx
```html
<div id="PseudoDialogTitle"></div>
```

- myYesNoMessageDialog.aspx
```html
<div id="PseudoDialogTitle" style="font-size: large"></div>
```

Comment (daisukenishino) [inline root/programs/C#/Samples/WebApp_sample/ProjectX_sample/Aspx/Framework/myOKMessageDialog.aspx]: @yusukemaegawa 

I edited this directly and added the following two commit.

- https://github.com/OpenTouryoProject/OpenTouryo/pull/237/commits/849fb09d715830f1aa049e2e9a6c3e6dd83cd3d2
- https://github.com/OpenTouryoProject/OpenTouryo/pull/237/commits/66ee77fe9646aebc7644846db6ddca75fc73e0c8
