### PR TITLE
Fixed : "The spelling of the property or the field is wrong." #108

### LINKED ISSUE #108: The spelling of the property or the field is wrong.
# Phenomenon
The spelling of the following property or field is wrong.
- [IsIndispensabile](https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/master/root_VS2013/programs/C%23/Frameworks/Infrastructure/CustomControl/PropertyGrid/CheckType.cs#L72) Property
- [IsIndispensabileCheckErrorMessage](https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/master/root_VS2013/programs/C%23/Frameworks/Infrastructure/CustomControl/Function/CmnCheckFunction.cs#L58) Field

There may be a similar spelling error elsewhere.

# Details
"Indispensabile" is wrong spelling.(This is the spelling of Italian.)
The correct spelling is "Indispensable".

### PR DESCRIPTION
**Pull request by daisukenishino**
fixed #108

### CODE REVIEW

**Comment by daisukenishino** [comment]
@yusukemaegawa 

I have the following checks.
- I ran grep in the under the root folder "dispensabile".
- I have searched "dispensable" after displaying the following URL.  
https://github.com/OpenTouryoProject/OpenTouryo/pull/147/files
  - Line after the change that starts with '+' has been confirmed that it is all highlights.
  - However except for the comment ( "Corrected IsIndispensabile property spelling" ).

File: root/programs/C#/Frameworks/Infrastructure/CustomControl/PropertyGrid/CheckType.cs [hunk 1]
```diff
@@ -64,21 +64,21 @@ public CheckType()
...
 
         /// <summary>必須</summary>
-        private bool _isIndispensabile;
+        private bool _isIndispensable;
 
         /// <summary>必須</summary>
         [DefaultValue(false), NotifyParentProperty(true),
         RefreshProperties(RefreshProperties.Repaint)]
-        public bool IsIndispensabile
+        public bool IsIndispensable
```
Comment (yusukemaegawa) [inline root/programs/C#/Frameworks/Infrastructure/CustomControl/PropertyGrid/CheckType.cs]: @daisukenishino 

I think that "Required" is more general than "Indispensable".
Microsoft also uses "Required" for the name of properties.

e.g. 
- [DataMemberAttribute.IsRequired プロパティ](https://msdn.microsoft.com/ja-jp/library/system.runtime.serialization.datamemberattribute.isrequired(v=vs.110).aspx)
- [MetaColumn.RequiredErrorMessage プロパティ](https://msdn.microsoft.com/ja-jp/library/system.web.dynamicdata.metacolumn.requirederrormessage(v=vs.100).aspx)

File: root/programs/VB/Frameworks/Infrastructure/CustomControl/RichClient/PropertyGrid/CheckType.vb [hunk 2]
```diff
@@ -42,215 +42,215 @@ Imports System.Windows
...
-				hc += 32
-			End If
-			If Me.IsHiragana Then
-				hc += 64
-			End If
-			If Me.IsDate Then
-				hc += 128
-			End If
+            If Me.IsIndispensable Then
+                hc += 1
```
Comment (yusukemaegawa) [inline root/programs/VB/Frameworks/Infrastructure/CustomControl/RichClient/PropertyGrid/CheckType.vb]: @daisukenishino 

How about using enumeration here?

File: root/programs/C#/Frameworks/Infrastructure/CustomControl/Control/WebCustomTextBox.cs [hunk 3]
```diff
@@ -326,12 +326,12 @@ public bool Validate(out string[] result)
             if (this.CheckType != null)
             {
                 // 必須入力チェック
-                if (this.CheckType.IsIndispensabile)
+                if (this.CheckType.IsIndispensable)
                 {
                     if ((text == ""))
```
Comment (yusukemaegawa) [inline root/programs/C#/Frameworks/Infrastructure/CustomControl/Control/WebCustomTextBox.cs]: @daisukenishino 

Is the value of the field "text" not null?
If no, you should use string.IsNullOrEmpty method.

File: root/programs/C#/Frameworks/Infrastructure/CustomControl/Control/WebCustomTextBox.cs [hunk 4]
```diff
@@ -326,12 +326,12 @@ public bool Validate(out string[] result)
...
                     {
                         hasError = true;
-                        lstRet.Add(CmnCheckFunction.IsIndispensabileCheckErrorMessage);
+                        lstRet.Add(CmnCheckFunction.IsIndispensableCheckErrorMessage);
```
Comment (yusukemaegawa) [inline root/programs/C#/Frameworks/Infrastructure/CustomControl/Control/WebCustomTextBox.cs]: @daisukenishino 

I think that the field "lstRet" is unnecessary.
- The type of argument "result" should be List<string>
- ErrorMessage should be added in "result" directly.

File: root/programs/C#/Frameworks/Infrastructure/CustomControl/Control/WebCustomTextBox.cs (hunk 3 above)
Comment (daisukenishino) [inline root/programs/C#/Frameworks/Infrastructure/CustomControl/Control/WebCustomTextBox.cs]: @yusukemaegawa 

I think that this.Text ( WebCustomTextBox.Text ) never become null.

File: root/programs/C#/Frameworks/Infrastructure/CustomControl/PropertyGrid/CheckType.cs (hunk 1 above)
Comment (daisukenishino) [inline root/programs/C#/Frameworks/Infrastructure/CustomControl/PropertyGrid/CheckType.cs]: @yusukemaegawa 
https://github.com/OpenTouryoProject/OpenTouryo/issues/148

File: root/programs/C#/Frameworks/Infrastructure/CustomControl/Control/WebCustomTextBox.cs (hunk 4 above)
Comment (daisukenishino) [inline root/programs/C#/Frameworks/Infrastructure/CustomControl/Control/WebCustomTextBox.cs]: @yusukemaegawa 

Since this is OUT parameter, the instance of result parameter does not divert.
In addition, by using the List <string> type internally, the return value uses the string [] type.

File: root/programs/VB/Frameworks/Infrastructure/CustomControl/RichClient/PropertyGrid/CheckType.vb (hunk 2 above)
Comment (daisukenishino) [inline root/programs/VB/Frameworks/Infrastructure/CustomControl/RichClient/PropertyGrid/CheckType.vb]: @yusukemaegawa 

Do you think that this pointed out is needed to add issue with label of the "quality improvement" ?

**Comment by daisukenishino** [comment]
@yusukemaegawa 

Plsease merge, if there is no problem.

File: root/programs/C#/Frameworks/Infrastructure/CustomControl/PropertyGrid/CheckType.cs (hunk 1 above)
Comment (yusukemaegawa) [inline root/programs/C#/Frameworks/Infrastructure/CustomControl/PropertyGrid/CheckType.cs]: @daisukenishino 

What do you want to say?
Please explain this sentence to me.

File: root/programs/C#/Frameworks/Infrastructure/CustomControl/Control/WebCustomTextBox.cs (hunk 3 above)
Comment (yusukemaegawa) [inline root/programs/C#/Frameworks/Infrastructure/CustomControl/Control/WebCustomTextBox.cs]: @daisukenishino 

I cannot understand what you want to say.
Is this sentence a translation done by a machine?

File: root/programs/C#/Frameworks/Infrastructure/CustomControl/Control/WebCustomTextBox.cs (hunk 4 above)
Comment (yusukemaegawa) [inline root/programs/C#/Frameworks/Infrastructure/CustomControl/Control/WebCustomTextBox.cs]: @daisukenishino 

Should be the type of "result" parameter "string[]"?
The following code does not use "lstRet".

```c#
public bool Validate(out List<string> result)
{
    // フラグ
    bool hasError = false;
    // 結果
    result = new List<string>();

    // omit

    hasError = true;
    result.Add(CmnCheckFunction.xxx);

    // omit

    return !hasError;
}
```

Comment (daisukenishino) [inline root/programs/C#/Frameworks/Infrastructure/CustomControl/Control/WebCustomTextBox.cs]: @yusukemaegawa 

I know. But, how to deal is unknown.
I think this pointed out should not be corresponded in this pullrequest.
Do you want to create a new issue?

File: root/programs/C#/Frameworks/Infrastructure/CustomControl/PropertyGrid/CheckType.cs (hunk 1 above)
Comment (daisukenishino) [inline root/programs/C#/Frameworks/Infrastructure/CustomControl/PropertyGrid/CheckType.cs]: @yusukemaegawa 

>https://github.com/OpenTouryoProject/OpenTouryo/issues/148

This request was registered as a problem that has been granted to quality improvement label.

- [Problem of the properties of a custom control](https://github.com/OpenTouryoProject/OpenTouryo/issues/148)

File: root/programs/C#/Frameworks/Infrastructure/CustomControl/Control/WebCustomTextBox.cs (hunk 3 above)
Comment (daisukenishino) [inline root/programs/C#/Frameworks/Infrastructure/CustomControl/Control/WebCustomTextBox.cs]: @yusukemaegawa 

I have modified the [above comments](https://github.com/OpenTouryoProject/OpenTouryo/pull/147#discussion_r51259469).

Please check.

File: root/programs/VB/Frameworks/Infrastructure/CustomControl/RichClient/PropertyGrid/CheckType.vb (hunk 2 above)
Comment (yusukemaegawa) [inline root/programs/VB/Frameworks/Infrastructure/CustomControl/RichClient/PropertyGrid/CheckType.vb]: @daisukenishino 

I think so.

File: root/programs/C#/Frameworks/Infrastructure/CustomControl/Control/WebCustomTextBox.cs (hunk 4 above)
Comment (yusukemaegawa) [inline root/programs/C#/Frameworks/Infrastructure/CustomControl/Control/WebCustomTextBox.cs]: @daisukenishino 

>I think this pointed out should not be corresponded in this pullrequest.

I see.
Please create new issue.

Comment (daisukenishino) [inline root/programs/C#/Frameworks/Infrastructure/CustomControl/Control/WebCustomTextBox.cs]: @yusukemaegawa

I've registered this to the [issue](https://github.com/OpenTouryoProject/OpenTouryo/issues/149#issuecomment-178399677).

File: root/programs/VB/Frameworks/Infrastructure/CustomControl/RichClient/PropertyGrid/CheckType.vb (hunk 2 above)
Comment (daisukenishino) [inline root/programs/VB/Frameworks/Infrastructure/CustomControl/RichClient/PropertyGrid/CheckType.vb]: @yusukemaegawa

I've registered this to the [issue](https://github.com/OpenTouryoProject/OpenTouryo/issues/148#issue-130225430).

**Comment by daisukenishino** [comment]
@yusukemaegawa 

Plsease merge, if there is no problem.
