### PR TITLE
Fixed : "To fix encryption wrapper library and tools." #203

### LINKED ISSUE #203: To fix encryption wrapper library and tools.
# Requirement

##### Overlord by stretching count.
- I want to be able to specify the stretching count as an argument of GetHash method by additional overlord method.
- This is because, There is the preferable to possible to specify the stretching count to GetSaltedPasswd method.
- Maintain backward compatibility by call additional overlord method as specify the number of times of stretching in existing method interface implementation to once.

##### Generating password method.
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Public/Util/GetHash.cs#L96
- Change Membership.GeneratePassword to RNGCryptoServiceProvider.
- Use an additional wrapper API for RNGCryptoServiceProvider.  

##### Add public property procedure for stretching count and salt.
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Public/Util/GetKeyedHash.cs#L77

##### Add HMAC Provider.
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Public/Util/GetKeyedHash.cs#L195

Only HMACSHA 1 is implemented.  
HMACMD5, HMACRIPEMD160, HMACSHA256, HMACSHA384, HMACSHA512 not yet implemented.

##### Changed generate method of keyed hash cryptographic provider.
This problems rediscovered by the above correspondence.
Because there was a problem that all factory method generated HMACSHA1.

##### Add GetSaltedPasswd and EqualSaltedPasswd.
Due to there was demand.

#### Related to CodeSigning.
- Add the following CodeSigningclasses.  
https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Frameworks/Infrastructure/Public/Util/CodeSigning

#### Related to JWT.
- Add the following JWT classes.  
https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Frameworks/Infrastructure/Public/Util/JWT

- Add ToBase64UrlString and FromBase64UrlString method to [CustomEncode](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Public/Str/CustomEncode.cs)  
There was need Base64Url to create JWT.

- Add  ToUnixTime and FromUnixTime method to [CustomEncode](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Public/Str/FormatConverter.cs)  
There are possibility to get unix time to create JWT.

#### Add GetPassword class that generate ramdom password by RNGCryptoServiceProvider.
- ASP.NETを使ってランダムなパスワードを生成する：CodeZine?（コードジン）  
https://codezine.jp/article/detail/238

# Tools
#### Be enable to specify stretching count from UI.
Add NumericUpDown control.

#### Add verification UI for GetSaltedPasswd and EqualSaltedPasswd API for GetKeyedHash
Add a new tab as the UI for the verification this feature.

#### Add verification UI for CodeSigning API .
Add a new tab as the UI for the verification this feature.

#### Add verification UI for JWT API .
Add a new tab as the UI for the verification this feature.

#### Fix following problem.
The password was specified at an argument specifying salt. Modify it to specify set as follows.

```CS
CustomEncode.StringToByte(this.txtKHSPassword.Text, CustomEncode.UTF_8)
```
▼
```CS
CustomEncode.StringToByte(this.txtKHSSalt.Text, CustomEncode.UTF_8)
```

#### Add
- Add multiple HMAC providers with keyed hash.
  - HMACMD5
  - HMACRIPEMD160
  - HMACSHA256
  - HMACSHA384
  - HMACSHA512

- Public-key cryptography
  - Add selection of hash algorithm for each provider of public-key cryptography.
  - Add verification code of execute "signature and verification" by public-key cryptography of ECDsaCng.

#### Delete
- AesCryptoServiceProvider

### PR DESCRIPTION
**Pull request by daisukenishino**
fixed #203

### CODE REVIEW

File: root/programs/C#/Frameworks/Infrastructure/Public/IO/ASymmetricCryptography.cs [hunk 1]
```diff
@@ -100,16 +102,20 @@ public static byte[] EncryptBytes(byte[] source, string publicKey)
...
                 = (RSACryptoServiceProvider)RSACryptoServiceProvider.Create(); // devps(1703)
-            
+
             // 公開鍵
             rsa.FromXmlString(publicKey);
 
-            // 暗号化する
+            // 暗号化する（XP以降の場合のみ2項目にTrueを指定し、OAEPパディングを使用できる）
             byte[] temp = rsa.Encrypt(source, false);
             rsa.Clear(); // devps(1725)
```
Comment (yusukemaegawa) [inline root/programs/C#/Frameworks/Infrastructure/Public/IO/ASymmetricCryptography.cs]: @daisukenishino 

Isn't it necessary to delete the key entry in the container?
See [MSDN](https://msdn.microsoft.com/en-us/library/tswxhw92(v=vs.110).aspx).

File: root/programs/C#/Frameworks/Infrastructure/Public/IO/SymmetricCryptography.cs [hunk 2]
```diff
@@ -64,8 +66,11 @@ namespace Touryo.Infrastructure.Public.IO
     /// </summary>
     public enum EnumSymmetricAlgorithm
     {
-        /// <summary>AesCryptoServiceProvider</summary>
-        AesCryptoServiceProvider,
+        // AesCryptoServiceProvider, AesManagedは3.5からの提供。
```
Comment (yusukemaegawa) [inline root/programs/C#/Frameworks/Infrastructure/Public/IO/SymmetricCryptography.cs]: @daisukenishino 

3.5 -> .NET Framework 3.5

File: root/programs/C#/Frameworks/Infrastructure/Public/IO/SymmetricCryptography.cs [hunk 3]
```diff
@@ -432,13 +438,15 @@ private static SymmetricAlgorithm CreateSymmetricAlgorithm(EnumSymmetricAlgorith
...
 
             // AesCryptoServiceProvider, AesManagedは3.5からの提供。
-
-            if (esa == EnumSymmetricAlgorithm.AesCryptoServiceProvider)
-            {
-                // AesCryptoServiceProviderサービスプロバイダ
-                sa = AesCryptoServiceProvider.Create(); // devps(1703)
-            }
-            else if (esa == EnumSymmetricAlgorithm.AesManaged)
+            // ポリシーに合わせて、AesCryptoServiceProviderを削除。
```
Comment (yusukemaegawa) [inline root/programs/C#/Frameworks/Infrastructure/Public/IO/SymmetricCryptography.cs]: @daisukenishino 

Where can I see this *policy*?

File: root/programs/C#/Frameworks/Infrastructure/Public/Util/CodeSigningX509.cs [hunk 4]
```diff
@@ -0,0 +1,198 @@
...
+            // アルゴリズム（RSA or DSA）は、ココで決まるもよう。
+            AsymmetricAlgorithm aa = this._X509Certificate.PrivateKey;
+
+            // 署名
+            byte[] signedByte = null;
+
+            if (aa is RSACryptoServiceProvider)
+            {
+                // RSACryptoServiceProvider : ExportParametersして生成し直している。
+                RSAParameters rsaPara = ((RSACryptoServiceProvider)(aa)).ExportParameters(true);
```
Comment (yusukemaegawa) [inline root/programs/C#/Frameworks/Infrastructure/Public/Util/CodeSigningX509.cs]: @daisukenishino 

rsaPara -> rsaParam

File: root/programs/C#/Frameworks/Infrastructure/Public/Util/CodeSigningX509.cs [hunk 5]
```diff
@@ -0,0 +1,198 @@
...
+                RSACryptoServiceProvider rsa = new RSACryptoServiceProvider(this._X509Certificate.PrivateKey.KeySize);
+                rsa.ImportParameters(rsaPara);
+                signedByte = rsa.SignData(data, this._hashAlgorithmName);
+            }
+            else
+            {
+                // DSACryptoServiceProvider : ExportParametersして生成し直している。
+                DSAParameters dsaPara = ((DSACryptoServiceProvider)(aa)).ExportParameters(true);
```
Comment (yusukemaegawa) [inline root/programs/C#/Frameworks/Infrastructure/Public/Util/CodeSigningX509.cs]: @daisukenishino

dsaPara -> dsaParam

File: root/programs/C#/Frameworks/Infrastructure/Public/Util/CodeSigningX509.cs [hunk 6]
```diff
@@ -0,0 +1,198 @@
...
+
+        /// <summary>Verify</summary>
+        /// <param name="data">data</param>
+        /// <param name="sign">署名</param>
+        /// <returns>検証結果</returns>
+        public override bool Verify(byte[] data, byte[] sign)
+        {
+            AsymmetricAlgorithm aa = null;
+
+            // 結果フラグ
```
Comment (yusukemaegawa) [inline root/programs/C#/Frameworks/Infrastructure/Public/Util/CodeSigningX509.cs]: @daisukenishino 

Please show the meaning of this flag.
Does *true* mean *success*?
Does *false* mean *failure*?

File: root/programs/C#/Frameworks/Infrastructure/Public/Util/CodeSigningXML.cs [hunk 7]
```diff
@@ -0,0 +1,274 @@
...
+// Unless required by applicable law or agreed to in writing, software
+// distributed under the License is distributed on an "AS IS" BASIS,
+// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+// See the License for the specific language governing permissions and
+// limitations under the License.
+//
+#endregion
+
+//**********************************************************************************
+//* クラス名        ：CodeSigning
```
Comment (yusukemaegawa) [inline root/programs/C#/Frameworks/Infrastructure/Public/Util/CodeSigningXML.cs]: @daisukenishino 

This class name is *CodeSigningXML*.

File: root/programs/C#/Frameworks/Infrastructure/Public/Util/CodeSigningXML.cs [hunk 8]
```diff
@@ -0,0 +1,274 @@
...
+                // 公開鍵をXML形式で取得
+                this.XMLPublicKey = this._aa.ToXmlString(false);
+            }
+        }
+
+        #endregion
+
+        #region 署名(XML)
+
+        /// <summary>Sign</summary>
```
Comment (yusukemaegawa) [inline root/programs/C#/Frameworks/Infrastructure/Public/Util/CodeSigningXML.cs]: @daisukenishino 

The term "Sign" is ambiguous.
(Does this method actually *sign*? Or, does this method create *digital signature*?)

At first sight, this method seems to create *digital signature*.
So, please write *'Create digital signature'* in *summary* tag and relating places.

File: root/programs/C#/Frameworks/Infrastructure/Public/Util/GetHash.cs [hunk 9]
```diff
@@ -82,40 +88,64 @@ public enum EnumHashAlgorithm
...
+                + "." + CustomEncode.ToBase64String(CustomEncode.StringToByte(stretchCount.ToString(), CustomEncode.UTF_8))
+                + "." + CustomEncode.ToBase64String(CustomEncode.StringToByte(GetHash.GetHashString(salt + rawPassword, eha, stretchCount), CustomEncode.UTF_8));
             // バイト配列仕様は、フィールドが文字列の可能性が高いので辞めた。
         }
 
         /// <summary>パスワードを比較して認証する。</summary>
-        /// <param name="rawPasswd">ユーザが入力した生のパスワード</param>
-        /// <param name="saltedPasswd">塩味パスワード</param>
+        /// <param name="rawPassword">ユーザが入力した生のパスワード</param>
+        /// <param name="saltedPassword">塩味パスワード</param>
```
Comment (yusukemaegawa) [inline root/programs/C#/Frameworks/Infrastructure/Public/Util/GetHash.cs]: @daisukenishino 

Please reconsider xml comment.

File: root/programs/C#/Frameworks/Infrastructure/Public/Util/GetHash.cs [hunk 10]
```diff
@@ -127,33 +157,75 @@ public static bool EqualSaltedPasswd(string rawPasswd, string saltedPasswd, Enum
...
+        #region String
+
         /// <summary>文字列のハッシュ値を計算して返す。</summary>
         /// <param name="sourceString">文字列</param>
         /// <param name="eha">ハッシュ・アルゴリズム列挙型</param>
         /// <returns>ハッシュ値（文字列）</returns>
         public static string GetHashString(string sourceString, EnumHashAlgorithm eha)
         {
-            // ハッシュ（Base64）
+            // overlordへ
```
Comment (yusukemaegawa) [inline root/programs/C#/Frameworks/Infrastructure/Public/Util/GetHash.cs]: @daisukenishino 

overlord -> overload

File: root/programs/C#/Frameworks/Infrastructure/Public/Util/GetPassword.cs [hunk 11]
```diff
@@ -0,0 +1,121 @@
...
+    /// <summary>GetPassword</summary>
+    public class GetPassword
+    {
+        /// <summary>Generate</summary>
+        /// <param name="length">長さ</param>
+        /// <param name="numberOfNonAlphanumericCharacters">Alphanumeric以外の文字数</param>
+        /// <returns>Password</returns>
+        public static string Generate(int length, int numberOfNonAlphanumericCharacters)
+        {
+            if (((length < 1) || (length > 128)))
```
Comment (yusukemaegawa) [inline root/programs/C#/Frameworks/Infrastructure/Public/Util/GetPassword.cs]: @daisukenishino 

There are too many parentheses.
```c#
if ((length < 1) || (length > 128))
```

File: root/programs/C#/Frameworks/Infrastructure/Public/Util/GetPassword.cs [hunk 12]
```diff
@@ -0,0 +1,121 @@
...
+            {
+                throw new ArgumentException("Password length is incorrect.");
+            }
+
+            if (((numberOfNonAlphanumericCharacters > length) || (numberOfNonAlphanumericCharacters < 0)))
```
Comment (yusukemaegawa) [inline root/programs/C#/Frameworks/Infrastructure/Public/Util/GetPassword.cs]: @daisukenishino

There are too many parentheses.

File: root/programs/C#/Frameworks/Infrastructure/Public/Util/GetPassword.cs [hunk 13]
```diff
@@ -0,0 +1,121 @@
+﻿//**********************************************************************************
+//* Copyright (C) 2007,2016 Hitachi Solutions,Ltd.
```
Comment (yusukemaegawa) [inline root/programs/C#/Frameworks/Infrastructure/Public/Util/GetPassword.cs]: @daisukenishino 

2016 -> 2017

File: root/programs/C#/Frameworks/Infrastructure/Public/Util/JWT.cs [hunk 14]
```diff
@@ -0,0 +1,71 @@
...
+using Touryo.Infrastructure.Public.Log;
+using Touryo.Infrastructure.Public.Str;
+using Touryo.Infrastructure.Public.Util;
+
+namespace Touryo.Infrastructure.Public.Util.JWT
+{
+    /// <summary>JWT Header</summary>
+    public class Header
+    {
+        /// <summary>alg = HS256 or RS256</summary>
```
Comment (yusukemaegawa) [inline root/programs/C#/Frameworks/Infrastructure/Public/Util/JWT.cs]: @daisukenishino 

In *summary* tag, please write the meaning of this variable.

File: root/programs/C#/Frameworks/Infrastructure/Public/IO/ASymmetricCryptography.cs (hunk 1 above)
Comment (daisukenishino) [inline root/programs/C#/Frameworks/Infrastructure/Public/IO/ASymmetricCryptography.cs]: @yusukemaegawa 

This management task can be done outside this class library.

File: root/programs/C#/Frameworks/Infrastructure/Public/IO/SymmetricCryptography.cs (hunk 2 above)
Comment (daisukenishino) [inline root/programs/C#/Frameworks/Infrastructure/Public/IO/SymmetricCryptography.cs]: @yusukemaegawa 

I see.

File: root/programs/C#/Frameworks/Infrastructure/Public/IO/SymmetricCryptography.cs (hunk 3 above)
Comment (daisukenishino) [inline root/programs/C#/Frameworks/Infrastructure/Public/IO/SymmetricCryptography.cs]: @yusukemaegawa 

Cryptographic provider selection policy.
- Managed library is top priority.
- Then CSP library. Finally CNG library.
- There is a possibility that the priority of CSP and CNG will change in the future.

I will add an explanation about this.

File: root/programs/C#/Frameworks/Infrastructure/Public/Util/CodeSigningX509.cs (hunk 4 above)
Comment (daisukenishino) [inline root/programs/C#/Frameworks/Infrastructure/Public/Util/CodeSigningX509.cs]: @yusukemaegawa 

I see.

File: root/programs/C#/Frameworks/Infrastructure/Public/Util/CodeSigningX509.cs (hunk 5 above)
Comment (daisukenishino) [inline root/programs/C#/Frameworks/Infrastructure/Public/Util/CodeSigningX509.cs]: @yusukemaegawa

I see.

File: root/programs/C#/Frameworks/Infrastructure/Public/Util/CodeSigningX509.cs (hunk 6 above)
Comment (daisukenishino) [inline root/programs/C#/Frameworks/Infrastructure/Public/Util/CodeSigningX509.cs]: @yusukemaegawa 

Validation result flag
- true: Validation successful
- false: Validation failed

File: root/programs/C#/Frameworks/Infrastructure/Public/Util/CodeSigningXML.cs (hunk 8 above)
Comment (daisukenishino) [inline root/programs/C#/Frameworks/Infrastructure/Public/Util/CodeSigningXML.cs]: @yusukemaegawa 

I see.

File: root/programs/C#/Frameworks/Infrastructure/Public/Util/CodeSigningXML.cs (hunk 7 above)
Comment (daisukenishino) [inline root/programs/C#/Frameworks/Infrastructure/Public/Util/CodeSigningXML.cs]: @yusukemaegawa 

I changed the class name as follows.
- CodeSigning ---> DigitalSign
- CodeSigningXML ---> DigitalSignXML
- CodeSigningXML ---> DigitalSignX509

File: root/programs/C#/Frameworks/Infrastructure/Public/Util/GetHash.cs (hunk 10 above)
Comment (daisukenishino) [inline root/programs/C#/Frameworks/Infrastructure/Public/Util/GetHash.cs]: @yusukemaegawa 

I see.

File: root/programs/C#/Frameworks/Infrastructure/Public/Util/GetPassword.cs (hunk 11 above)
Comment (daisukenishino) [inline root/programs/C#/Frameworks/Infrastructure/Public/Util/GetPassword.cs]: @yusukemaegawa

I see.

Comment (daisukenishino) [inline root/programs/C#/Frameworks/Infrastructure/Public/Util/GetPassword.cs]: You have talent to find typo !

File: root/programs/C#/Frameworks/Infrastructure/Public/Util/GetPassword.cs (hunk 13 above)
Comment (daisukenishino) [inline root/programs/C#/Frameworks/Infrastructure/Public/Util/GetPassword.cs]: @yusukemaegawa 

For newly added classes, change from 2016 to 2017.
https://oshiete.goo.ne.jp/qa/5528706.html

File: root/programs/C#/Frameworks/Infrastructure/Public/Util/JWT.cs (hunk 14 above)
Comment (daisukenishino) [inline root/programs/C#/Frameworks/Infrastructure/Public/Util/JWT.cs]: @yusukemaegawa 

I see.

File: root/programs/C#/Frameworks/Infrastructure/Public/Util/GetPassword.cs (hunk 12 above)
Comment (daisukenishino) [inline root/programs/C#/Frameworks/Infrastructure/Public/Util/GetPassword.cs]: @yusukemaegawa

I see.

File: root/programs/C#/Frameworks/Infrastructure/Public/Util/GetHash.cs (hunk 9 above)
Comment (daisukenishino) [inline root/programs/C#/Frameworks/Infrastructure/Public/Util/GetHash.cs]: @yusukemaegawa 

I see.

Translation of "Salted and hashed password" was difficult.
Therefore, I will write in English.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

Please merge this pull request,
since I have pushed one commit.

File: root/programs/C#/Frameworks/Infrastructure/Public/IO/SymmetricCryptography.cs (hunk 3 above)
Comment (yusukemaegawa) [inline root/programs/C#/Frameworks/Infrastructure/Public/IO/SymmetricCryptography.cs]: @daisukenishino 

About AesCryptoServiceProvider class, [MSDN](https://msdn.microsoft.com/ja-jp/library/system.security.cryptography.aescryptoserviceprovider(v=vs.110).aspx) describes as follows:
```txt
Performs symmetric encryption and decryption using the Cryptographic Application Programming Interfaces (CAPI) implementation of the Advanced Encryption Standard (AES) algorithm.
```

Since AesCryptoServiceProvider class uses *CAPI*, I suggest that you add *CAPI* to policy.
- CAPI was replaced with CNG on Windows Vista or later.
- Before Windows Vista (e.g. Windows XP) support has ended.
- So, AesCryptoServiceProvider class, that uses *CAPI*, was deleted.

File: root/programs/C#/Frameworks/Infrastructure/Public/Util/CodeSigningXML.cs (hunk 8 above)
Comment (yusukemaegawa) [inline root/programs/C#/Frameworks/Infrastructure/Public/Util/CodeSigningXML.cs]: @daisukenishino 

I suggest that you rename this method to 'CreateDigitalSignature'.

File: root/programs/C#/Frameworks/Infrastructure/Public/Util/GetHash.cs (hunk 9 above)
Comment (yusukemaegawa) [inline root/programs/C#/Frameworks/Infrastructure/Public/Util/GetHash.cs]: @daisukenishino 

Could you revice the related code?
(e.g. [this code](https://github.com/OpenTouryoProject/OpenTouryo/pull/206/files#diff-cb6cd6992edec91f48dcce4b6a451444R107))

File: root/programs/C#/Frameworks/Infrastructure/Public/Util/DigitalSignXML.cs [hunk 15]
```diff
@@ -0,0 +1,274 @@
...
+using Touryo.Infrastructure.Public.Str;
+using Touryo.Infrastructure.Public.Util;
+
+using System.Security.Cryptography;
+using System.Security.Cryptography.X509Certificates;
+
+namespace Touryo.Infrastructure.Public.Util
+{
+    /// <summary>
+    /// CodeSigningXMLクラス
```
Comment (yusukemaegawa) [inline root/programs/C#/Frameworks/Infrastructure/Public/Util/DigitalSignXML.cs]: @daisukenishino 

CodeSigningXML -> DigitalSignXML

File: root/programs/C#/Frameworks/Infrastructure/Public/Util/JWT_RS256.cs [hunk 16]
```diff
@@ -0,0 +1,121 @@
...
+using Newtonsoft.Json;
+
+namespace Touryo.Infrastructure.Public.Util.JWT
+{
+    /// <summary>JWT_RS256</summary>
+    public class JWT_RS256 : JWT
+    {
+        #region mem & prop & constructor
+
+        /// <summary>RS256のJWTを作成するためのCodeSigningプロバイダ</summary>
```
Comment (yusukemaegawa) [inline root/programs/C#/Frameworks/Infrastructure/Public/Util/JWT_RS256.cs]: @daisukenishino

CodeSigning -> DigitalSign

File: root/programs/C#/Frameworks/Infrastructure/Public/Util/JWT_RS256.cs [hunk 17]
```diff
@@ -0,0 +1,121 @@
...
+        DigitalSign _cs = null;
+
+        /// <summary>検証用JWK</summary>
+        public string JWK = "";
+
+        /// <summary>Constructor</summary>
+        /// <param name="csRS256">RS256の署名・検証が可能なように設定されたCodeSigningオブジェクト</param>
```
Comment (yusukemaegawa) [inline root/programs/C#/Frameworks/Infrastructure/Public/Util/JWT_RS256.cs]: @daisukenishino

CodeSigning -> DigitalSign

File: root/programs/C#/Frameworks/Infrastructure/Public/IO/SymmetricCryptography.cs [hunk 18]
```diff
@@ -438,9 +438,9 @@ private static SymmetricAlgorithm CreateSymmetricAlgorithm(EnumSymmetricAlgorith
         {
             SymmetricAlgorithm sa = null;
 
-            // AesCryptoServiceProvider, AesManagedは3.5からの提供。
-            // 暗号化プロバイダ選択のポリシー（Managed → CSP → CNG）
-            // に合わせて、AesCryptoServiceProviderを削除。
+            // AesCryptoServiceProvider, AesManagedは.NET Framework 3.5からの提供。
+            // 暗号化プロバイダ選択の優先順は、Managed → CAPI(CSP) → CNG。
```
Comment (yusukemaegawa) [inline root/programs/C#/Frameworks/Infrastructure/Public/IO/SymmetricCryptography.cs]: @daisukenishino 

Is this order *ascending order*? Or *descending order*?
If *ascending order*, I suggest that you write '優先度は、低い順に…'.
If *descending order*, I suggest that you write '優先度は、高い順に…'.

Comment (yusukemaegawa) [inline root/programs/C#/Frameworks/Infrastructure/Public/IO/SymmetricCryptography.cs]: @daisukenishino 

If this order is *descending order*, is the priority of CAPI higher than CNG?
After Windows Vista, CAPI was replaced with CNG.
So, I suspect that the priority of CNG is higher than CAPI.

Comment (daisukenishino) [inline root/programs/C#/Frameworks/Infrastructure/Public/IO/SymmetricCryptography.cs]: @yusukemaegawa 

Windows 2003 and XP also fall within the scope of support for the previous .NET 2.0 - 3.5 support range. So, I had been decided not to adopt CNG adoption.
Now, since the support range has reached .NET 4.6 or later, the support range OS has become Vista or later. Therefore, in the future, I will switch from CAPI to CNG.

Comment (daisukenishino) [inline root/programs/C#/Frameworks/Infrastructure/Public/IO/SymmetricCryptography.cs]: @yusukemaegawa 

I've written a verification code for electronic signature processing with TestEncAndDecProvider.
Https://github.com/OpenTouryoProject/OpenTouryo/blob/MaintainingEncLib/root/programs/C%23/Frameworks/Tools/Encryption/TestEncAndDecProvider/Form1.cs#L1427

However, changes to the CNG library did not work just by replacing classes, as the interface change was great.

Comment (daisukenishino) [inline root/programs/C#/Frameworks/Infrastructure/Public/IO/SymmetricCryptography.cs]: @yusukemaegawa 

There are features to develop immediately with RSACryptoServiceProvider.
However, RSACryptoServiceProvider has not been CNG compliant yet.

I am aware of the change in the priority of CAPI and CNG, but I'd like you to merge for now for the following reasons.

- It takes a lot of time to change from CAPI to CNG.
- Development of the above functions has priority.

For coping with changes in priorities of CAPI and CNG, they will be registered as issues.

File: root/programs/C#/Frameworks/Infrastructure/Public/IO/ASymmetricCryptography.cs (hunk 1 above)
Comment (daisukenishino) [inline root/programs/C#/Frameworks/Infrastructure/Public/IO/ASymmetricCryptography.cs]: @yusukemaegawa 

I see.
Add ".PersistInCsp = false" before Clear () method.
